In [0]:
import numpy as np

In [0]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

In [0]:
x=arr1.shape[1] # Storing Number Of Columns
y=[n for n in range(0,x,2)] # Using range function to generate a list with alternate values
arr1[:,y] # Fancy Indexing

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

In [0]:
x=arr1[[0,3,6],] #to select 1st row, 4th row and 7th row and store it in x
x
x[:,[0,2,4]] #to select alternate column starting from col1 from x

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [0]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[6211, 6452, 7327, 6327, 3086],
       [6506, 5124, 1078, 2665, 1745]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.

In [0]:
Xmin=arr2.min() # Minimum Value
Xmax=arr2.max() # Maximum Value
x=Xmax-Xmin
np.array([(i-Xmin)/x for i in np.nditer(arr2)]).reshape(arr2.shape) # Applying operation on each element of arr2, converting it to 1D array and then reshaping to arr2 again

array([[0.82141143, 0.8599776 , 1.        , 0.8399744 , 0.32133141],
       [0.86861898, 0.64746359, 0.        , 0.25396063, 0.10673708]])

In [0]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai

In [0]:
import numpy as np
arr3=np.arange(6.0,15.0).reshape(3,3) # Contanins nan
arr3[2][0] = np.nan
arr5 = np.arange(6.0,15.0).reshape(3,3) # Doesn't contain nan
print("Array 5 doesn't contain nan so false : ", np.isnan(arr5).any()) # np.isnan() function returns Boolean array and using any() function to check if boolean array contains True or not
print("Array 3 contains nan so true : ", np.isnan(arr3).any())

Array 5 doesn't contain nan so false :  False
Array 3 contains nan so true :  True


In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [0]:
def x(arr,n):
    arr.sort() # SOrting array
    return(arr[-n]) # Using negative indexing to return nth largest element

In [0]:
arr10=np.array([5,6,14,35,7,91,15,60])
x(arr10, 5)

14