In [41]:
import numpy as np

In [42]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing
arr1[:,[3,1,2,0,4]]

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [10]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row
# Method 1: when the number of rows is known
arr1[[3,2,1,0]]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [43]:
#Method 2: when the number of rows is unknown
x=arr1.shape[0] # To get number of rows
y=[n for n in range(x-1,-1,-1)] # List of reverse indexing 3,2,1,0
arr1[y] # Fancy indexing

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [44]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [51]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2
mean=np.nanmean(arr2) # Mean not considering nan values 
arr2[np.isnan(arr2)]=mean # Assigning mean to nan values using concept of boolean indexing
arr2

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [52]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[ 4,  9, 57, 30],
       [41, 56, 99, 59],
       [55, 93, 84, 26],
       [64, 94, 85, 30],
       [36, 36, 14, 63]])

In [53]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3
arr3[(arr3 >= 25)|(arr3%3==0)] # Boolean indexing

array([ 9, 57, 30, 41, 56, 99, 59, 55, 93, 84, 26, 64, 94, 85, 30, 36, 36,
       63])

In [54]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile
np.percentile(arr3, [10,25,50]) # Passing list of percentiles we want to know in list to np.percentile() function

array([13.5, 30. , 55.5])